package com.eldersphere.enums;

import java.util.HashMap;
import java.util.Map;

public enum ExceptionCodeEnum {

    // ==== COMMON / SYSTEM ERRORS ====
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),
    UNEXPECTED_ERROR("UNEXPECTED_ERROR"),
    DATABASE_ERROR("DATABASE_ERROR"),
    NULL_POINTER("NULL_POINTER"),
    MAPPING_ERROR("MAPPING_ERROR"),
    FORMAT_ERROR("FORMAT_ERROR"),

    // ==== AUTH & SECURITY ====
    UNAUTHORIZED("UNAUTHORIZED"),
    INVALID_CREDENTIALS("INVALID_CREDENTIALS"),
    TOKEN_EXPIRED("TOKEN_EXPIRED"),
    TOKEN_INVALID("TOKEN_INVALID"),
    FORBIDDEN("FORBIDDEN"),

    // ==== USER ====
    USER_NOT_FOUND("USER_NOT_FOUND"),
    DUPLICATE_EMAIL("DUPLICATE_EMAIL"),
    ADMIN_ALREADY_EXISTS("ADMIN_ALREADY_EXISTS"),

    // ==== ROLE / PERMISSION ====
    ROLE_NOT_FOUND("ROLE_NOT_FOUND"),
    DUPLICATE_ROLE("DUPLICATE_ROLE"),
    PERMISSION_NOT_FOUND("PERMISSION_NOT_FOUND"),
    DUPLICATE_PERMISSION("DUPLICATE_PERMISSION"),
    ROLE_PERMISSION_NOT_FOUND("ROLE_PERMISSION_NOT_FOUND"),
    DUPLICATE_ROLE_PERMISSION("DUPLICATE_ROLE_PERMISSION"),

    // ==== USER ROLE MAPPINGS (multi-role) ====
    USER_ROLE_ALREADY_ASSIGNED("USER_ROLE_ALREADY_ASSIGNED"),
    USER_ROLE_NOT_ASSIGNED("USER_ROLE_NOT_ASSIGNED"),
    USER_ROLE_NOT_HELD("USER_ROLE_NOT_HELD"),
    LAST_USER_ROLE_CANNOT_BE_REVOKED("LAST_USER_ROLE_CANNOT_BE_REVOKED"),
    PRIMARY_USER_ROLE_CANNOT_BE_REVOKED("PRIMARY_USER_ROLE_CANNOT_BE_REVOKED"),

    // ==== CARETAKER / ELDER ====
    CARETAKER_PROFILE_NOT_FOUND("CARETAKER_PROFILE_NOT_FOUND"),
    DUPLICATE_CARETAKER_PROFILE("DUPLICATE_CARETAKER_PROFILE"),
    ELDER_PROFILE_NOT_FOUND("ELDER_PROFILE_NOT_FOUND"),

    // ==== ELDER/FAMILY LINK INVITES ====
    ELDER_PROFILE_LINK_INVITE_NOT_FOUND("ELDER_PROFILE_LINK_INVITE_NOT_FOUND"),
    INVITE_ALREADY_RESPONDED("INVITE_ALREADY_RESPONDED"),
    DUPLICATE_INVITE("DUPLICATE_INVITE"),
    ELDER_ALREADY_LINKED("ELDER_ALREADY_LINKED"),
    FAMILY_MEMBER_ALREADY_LINKED("FAMILY_MEMBER_ALREADY_LINKED"),
    INVALID_INVITE_ROLE("INVALID_INVITE_ROLE"),

    // ==== SERVICE / BOOKING ====
    SERVICE_OFFERING_NOT_FOUND("SERVICE_OFFERING_NOT_FOUND"),
    NAV_LINK_NOT_FOUND("NAV_LINK_NOT_FOUND"),
    BOOKING_NOT_FOUND("BOOKING_NOT_FOUND"),
    INVALID_BOOKING_STATUS_TRANSITION("INVALID_BOOKING_STATUS_TRANSITION"),
    BOOKING_CONFLICT("BOOKING_CONFLICT"),
    CARETAKER_UNAVAILABLE("CARETAKER_UNAVAILABLE"),

    // ==== FAVORITE CARETAKERS ====
    DUPLICATE_FAVORITE_CARETAKER("DUPLICATE_FAVORITE_CARETAKER"),
    FAVORITE_CARETAKER_NOT_FOUND("FAVORITE_CARETAKER_NOT_FOUND"),

    // ==== MEDICAL / REVIEW / EMERGENCY ====
    MEDICAL_RECORD_NOT_FOUND("MEDICAL_RECORD_NOT_FOUND"),
    REVIEW_NOT_FOUND("REVIEW_NOT_FOUND"),
    DUPLICATE_REVIEW("DUPLICATE_REVIEW"),
    EMERGENCY_ALERT_NOT_FOUND("EMERGENCY_ALERT_NOT_FOUND"),

    // ==== PAYMENT ====
    PAYMENT_NOT_FOUND("PAYMENT_NOT_FOUND"),
    PAYMENT_GATEWAY_NOT_CONFIGURED("PAYMENT_GATEWAY_NOT_CONFIGURED"),
    PAYMENT_ALREADY_SUCCEEDED("PAYMENT_ALREADY_SUCCEEDED"),
    BOOKING_NOT_PAYABLE("BOOKING_NOT_PAYABLE"),
    PAYMENT_NOT_REFUNDABLE("PAYMENT_NOT_REFUNDABLE"),
    WEBHOOK_SIGNATURE_INVALID("WEBHOOK_SIGNATURE_INVALID"),

    // ==== NOTIFICATION ====
    NOTIFICATION_NOT_FOUND("NOTIFICATION_NOT_FOUND"),

    // ==== MESSAGING ====
    CONVERSATION_NOT_FOUND("CONVERSATION_NOT_FOUND"),
    MESSAGE_NOT_FOUND("MESSAGE_NOT_FOUND"),

    // ==== CARETAKER AVAILABILITY ====
    CARETAKER_AVAILABILITY_NOT_FOUND("CARETAKER_AVAILABILITY_NOT_FOUND"),

    // ==== REVIEW REPLY ====
    REVIEW_REPLY_NOT_FOUND("REVIEW_REPLY_NOT_FOUND"),
    DUPLICATE_REVIEW_REPLY("DUPLICATE_REVIEW_REPLY"),

    // ==== LANDING PAGE ====
    LANDING_FEATURE_NOT_FOUND("LANDING_FEATURE_NOT_FOUND"),
    LANDING_FAQ_NOT_FOUND("LANDING_FAQ_NOT_FOUND"),
    LANDING_TESTIMONIAL_NOT_FOUND("LANDING_TESTIMONIAL_NOT_FOUND"),

    // ==== COLOR THEME ====
    COLOR_THEME_NOT_FOUND("COLOR_THEME_NOT_FOUND"),
    DUPLICATE_COLOR_THEME("DUPLICATE_COLOR_THEME"),
    CANNOT_DELETE_DEFAULT_COLOR_THEME("CANNOT_DELETE_DEFAULT_COLOR_THEME"),
    COLOR_THEME_INACTIVE("COLOR_THEME_INACTIVE"),

    // ==== CONTACT US ====
    CONTACT_US_NOT_FOUND("CONTACT_US_NOT_FOUND"),

    // ==== FILE ====
    FILE_NOT_FOUND("FILE_NOT_FOUND"),
    FILE_STORAGE_FAILED("FILE_STORAGE_FAILED"),

    // ==== VALIDATION / INPUT ====
    BAD_REQUEST("BAD_REQUEST"),
    INVALID_ARGUMENT("INVALID_ARGUMENT"),
    VALIDATION_FAILED("VALIDATION_FAILED"),
    PASSWORD_TOO_WEAK("PASSWORD_TOO_WEAK"),
    PASSWORD_MISMATCH("PASSWORD_MISMATCH"),
    PASSWORD_RESET_FAILED("PASSWORD_RESET_FAILED"),
    DATA_NOT_FOUND("DATA_NOT_FOUND");

    private final String value;

    private static final Map<String, ExceptionCodeEnum> valueToEnumMap = new HashMap<>();

    static {
        for (ExceptionCodeEnum code : ExceptionCodeEnum.values()) {
            valueToEnumMap.put(code.getValue().toUpperCase(), code);
        }
    }

    ExceptionCodeEnum(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    public static ExceptionCodeEnum fromValue(String value) {
        ExceptionCodeEnum code = valueToEnumMap.get(value.toUpperCase());
        if (code != null) {
            return code;
        }
        throw new IllegalArgumentException("Invalid exception code: " + value);
    }
}
