package com.eldersphere.enums;

public enum NotificationTypeEnum {
    BOOKING_CONFIRMED,
    BOOKING_REMINDER,
    EMERGENCY_ALERT,
    NEW_MESSAGE,
    GENERAL,
    ELDER_LINK_INVITE,
    ELDER_LINK_ACCEPTED,
    ELDER_LINK_DECLINED,
    PAYMENT_RECEIVED,
    PAYMENT_FAILED
}
